apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database-name: BeStrong-DB
  mongo-initdb.js: |
    db = db.getSiblingDB('BeStrong-DB');
    db.createCollection('BeStrong-DB');
